### ISSUE TITLE
Python 3.12 support

### ISSUE THREAD

**Issue by gitoss** [lyckantropen/psnr_hvsm#4]
If anyone was wondering if there's interest in updated, current Python support - there is :-)

**Comment by lyckantropen** [comment]
Thanks for your interest! I've added 3.12, packages should be up once the CI completes.

**Comment by gitoss** [comment]
Thanks!

The psnr_hvsm py depends defnitely and unequivocally on 1.x numpy?

```
Collecting psnr-hvsm
  Using cached psnr_hvsm-0.2.2-cp312-cp312-win_amd64.whl.metadata (8.7 kB)
Collecting numpy<2,>=1.18 (from psnr-hvsm)
  Using cached numpy-1.26.4-cp312-cp312-win_amd64.whl.metadata (61 kB)
Collecting msvc-runtime>=14 (from psnr-hvsm)
  Using cached msvc_runtime-14.40.33807-cp312-cp312-win_amd64.whl.metadata (461 bytes)
Using cached psnr_hvsm-0.2.2-cp312-cp312-win_amd64.whl (2.4 MB)
Using cached msvc_runtime-14.40.33807-cp312-cp312-win_amd64.whl (1.9 MB)
Using cached numpy-1.26.4-cp312-cp312-win_amd64.whl (15.5 MB)
Installing collected packages: numpy, msvc-runtime, psnr-hvsm
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.0
    Uninstalling numpy-2.0.0:
      Successfully uninstalled numpy-2.0.0
Successfully installed msvc-runtime-14.40.33807 numpy-1.26.4 psnr-hvsm-0.2.2

```

**Comment by lyckantropen** [comment]
As of now, yes. It probably doesn't have to. I've just not had the time to
look into changes in NumPy 2.0. If I update, I'd like to keep support for
1.x. 2.0 hasn't been out for long and I don't yet know if that's a problem
or not.

niedz., 23 cze 2024, 12:46 użytkownik gitoss ***@***.***>
napisał:

**Comment by lyckantropen** [comment]
Feel free to open a new issue for NumPy 2.0.

niedz., 23 cze 2024, 13:18 użytkownik Karol Trojanowski <
***@***.***> napisał:
